spring:
  application:
    name: hello-spring-cloud-zuul
  zipkin:
    base-url: http://localhost:9411

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zuul?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: root
    password: root
server:
  port: 8769

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

##动态路由配置，不在从配置文件加载：ZuulRouteLocator
#zuul:
#  routes:
#    api-a:
#      path: /api/a/**
#      serviceId: hello-spring-cloud-web-admin-ribbon
#    api-b:
#      path: /api/b/**
#      serviceId: hello-spring-cloud-web-admin-feign
#    api-c:
#      path: /api/c/**
#      serviceId: hello-spring-cloud-service