server:
    port: 8080
spring:
    application:
        name: api-gateway
    cloud:
        gateway:
            discovery:
                locator:
                    enabled: true
            routes:
                - id: hello-spring-cloud-web-admin-feign
                  uri: lb://hello-spring-cloud-web-admin-feign
                  order: 0
                  predicates:
                      - Path=/api/user/**
                  filters:
                    - StripPrefix=1
                    - AddResponseHeader=X-Response-Default-Foo, Default-Bar
                - id: test
                  uri: https://blog.csdn.net
                  predicates:
                      - Path=/meteor_93

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/